/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
/**
 *
 * @author Salva
 */
import Controlador.AccesoBD;
import Modelo.Empleado;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
public class InterfazGrafica extends javax.swing.JFrame {
    private AccesoBD bd = new AccesoBD();
    private ArrayList<Empleado> lista = new ArrayList<>();
    private ArrayList<Empleado> listaAux = new ArrayList<>();
    SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");

    private Empleado actual = new Empleado();
    private int indice = 0;
    
    /**
     * Creates new form InterfazGraficas
     */
    public InterfazGrafica() {
        super("Gestion Empleados");
        initComponents();
        //cambiarContenedor(Bienvenida);
        cambiarContenedor(InicioSesion);
        Barra.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenida = new javax.swing.JPanel();
        Version = new javax.swing.JLabel();
        Autores = new javax.swing.JLabel();
        MyTitle = new javax.swing.JLabel();
        Gestiontittle = new javax.swing.JLabel();
        VIndividualJPanel = new javax.swing.JPanel();
        TituloIndividual = new javax.swing.JLabel();
        NumeroLabel = new javax.swing.JLabel();
        ApellidoLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        SueldoLabel = new javax.swing.JLabel();
        SueldoMaxLabel = new javax.swing.JLabel();
        FechaField = new javax.swing.JTextField();
        NumeroField = new javax.swing.JTextField();
        NombreField = new javax.swing.JTextField();
        ApellidoField = new javax.swing.JTextField();
        SueldoField = new javax.swing.JTextField();
        FechaLabel = new javax.swing.JLabel();
        RetrocederButton = new javax.swing.JButton();
        AvanzarButton = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();
        SueldoMaxField = new javax.swing.JTextField();
        jComboBoxFiltrarApellido = new javax.swing.JComboBox<>();
        FiltrarApellidoButton = new javax.swing.JButton();
        VCompletoPanel = new javax.swing.JPanel();
        TituloIndividual1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jlist = new javax.swing.JList<>();
        SueldoLabel1 = new javax.swing.JLabel();
        SueldoLabel2 = new javax.swing.JLabel();
        jDateHasta = new com.toedter.calendar.JDateChooser();
        jDateDesde = new com.toedter.calendar.JDateChooser();
        FiltrarButton = new javax.swing.JButton();
        InicioSesion = new javax.swing.JPanel();
        jTextFieldUsuario = new javax.swing.JTextField();
        AccederButton = new javax.swing.JButton();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        MyTitle1 = new javax.swing.JLabel();
        jTextFieldContraseña = new javax.swing.JPasswordField();
        Barra = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        VisualizarIndividual = new javax.swing.JMenu();
        VisualizarCompleto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Bienvenida.setBackground(new java.awt.Color(41, 44, 51));
        Bienvenida.setPreferredSize(new java.awt.Dimension(898, 575));

        Version.setBackground(new java.awt.Color(102, 102, 102));
        Version.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        Version.setForeground(new java.awt.Color(204, 204, 204));
        Version.setText(" V 1.0");

        Autores.setBackground(new java.awt.Color(102, 102, 102));
        Autores.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        Autores.setForeground(new java.awt.Color(204, 204, 204));
        Autores.setText("SALVADOR GARCÍA & BRUNO LÓPEZ");

        MyTitle.setBackground(new java.awt.Color(153, 153, 255));
        MyTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 90)); // NOI18N
        MyTitle.setForeground(new java.awt.Color(237, 187, 88));
        MyTitle.setText("My");

        Gestiontittle.setBackground(new java.awt.Color(153, 153, 255));
        Gestiontittle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 90)); // NOI18N
        Gestiontittle.setForeground(new java.awt.Color(204, 204, 204));
        Gestiontittle.setText("Gestion");

        javax.swing.GroupLayout BienvenidaLayout = new javax.swing.GroupLayout(Bienvenida);
        Bienvenida.setLayout(BienvenidaLayout);
        BienvenidaLayout.setHorizontalGroup(
            BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BienvenidaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Version)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BienvenidaLayout.createSequentialGroup()
                .addContainerGap(1131, Short.MAX_VALUE)
                .addGroup(BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BienvenidaLayout.createSequentialGroup()
                        .addComponent(Autores)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BienvenidaLayout.createSequentialGroup()
                        .addComponent(MyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gestiontittle, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );
        BienvenidaLayout.setVerticalGroup(
            BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BienvenidaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Version)
                .addGap(140, 140, 140)
                .addGroup(BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gestiontittle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 718, Short.MAX_VALUE)
                .addComponent(Autores)
                .addGap(28, 28, 28))
        );

        VIndividualJPanel.setBackground(new java.awt.Color(41, 44, 51));
        VIndividualJPanel.setForeground(new java.awt.Color(51, 51, 51));
        VIndividualJPanel.setToolTipText("");
        VIndividualJPanel.setPreferredSize(new java.awt.Dimension(898, 575));

        TituloIndividual.setBackground(new java.awt.Color(153, 153, 255));
        TituloIndividual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        TituloIndividual.setForeground(new java.awt.Color(237, 187, 88));
        TituloIndividual.setText("VISUALIZAR INDIVIDUAL");

        NumeroLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        NumeroLabel.setForeground(new java.awt.Color(204, 204, 204));
        NumeroLabel.setText("Número");

        ApellidoLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        ApellidoLabel.setForeground(new java.awt.Color(204, 204, 204));
        ApellidoLabel.setText("Apellido");

        NombreLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(204, 204, 204));
        NombreLabel.setText("Nombre");

        SueldoLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        SueldoLabel.setForeground(new java.awt.Color(204, 204, 204));
        SueldoLabel.setText("Sueldo");

        SueldoMaxLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        SueldoMaxLabel.setForeground(new java.awt.Color(204, 204, 204));
        SueldoMaxLabel.setText("Sueldo Max");

        FechaField.setEditable(false);
        FechaField.setBackground(new java.awt.Color(204, 204, 204));
        FechaField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FechaField.setForeground(new java.awt.Color(51, 51, 51));

        NumeroField.setEditable(false);
        NumeroField.setBackground(new java.awt.Color(204, 204, 204));
        NumeroField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NumeroField.setForeground(new java.awt.Color(51, 51, 51));
        NumeroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroFieldActionPerformed(evt);
            }
        });

        NombreField.setEditable(false);
        NombreField.setBackground(new java.awt.Color(204, 204, 204));
        NombreField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreField.setForeground(new java.awt.Color(51, 51, 51));

        ApellidoField.setEditable(false);
        ApellidoField.setBackground(new java.awt.Color(204, 204, 204));
        ApellidoField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ApellidoField.setForeground(new java.awt.Color(51, 51, 51));

        SueldoField.setEditable(false);
        SueldoField.setBackground(new java.awt.Color(204, 204, 204));
        SueldoField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SueldoField.setForeground(new java.awt.Color(51, 51, 51));

        FechaLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        FechaLabel.setForeground(new java.awt.Color(204, 204, 204));
        FechaLabel.setText("Fecha de Alta");

        RetrocederButton.setBackground(new java.awt.Color(56, 67, 75));
        RetrocederButton.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        RetrocederButton.setForeground(new java.awt.Color(255, 255, 255));
        RetrocederButton.setText("Retroceder");
        RetrocederButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrocederButtonActionPerformed(evt);
            }
        });

        AvanzarButton.setBackground(new java.awt.Color(56, 67, 75));
        AvanzarButton.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        AvanzarButton.setForeground(new java.awt.Color(255, 255, 255));
        AvanzarButton.setText("Avanzar");
        AvanzarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanzarButtonActionPerformed(evt);
            }
        });

        Imagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 4, true));

        SueldoMaxField.setEditable(false);
        SueldoMaxField.setBackground(new java.awt.Color(204, 204, 204));
        SueldoMaxField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SueldoMaxField.setForeground(new java.awt.Color(51, 51, 51));

        jComboBoxFiltrarApellido.setMaximumRowCount(500);

        FiltrarApellidoButton.setText("Filtrar");
        FiltrarApellidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrarApellidoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VIndividualJPanelLayout = new javax.swing.GroupLayout(VIndividualJPanel);
        VIndividualJPanel.setLayout(VIndividualJPanelLayout);
        VIndividualJPanelLayout.setHorizontalGroup(
            VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(RetrocederButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(AvanzarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VIndividualJPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                            .addComponent(ApellidoLabel)
                            .addGap(30, 30, 30)
                            .addComponent(ApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                            .addComponent(SueldoLabel)
                            .addGap(30, 30, 30)
                            .addComponent(SueldoField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                            .addComponent(NombreLabel)
                            .addGap(30, 30, 30)
                            .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                            .addComponent(NumeroLabel)
                            .addGap(30, 30, 30)
                            .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                                    .addComponent(jComboBoxFiltrarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(FiltrarApellidoButton))
                                .addComponent(NumeroField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 991, Short.MAX_VALUE)
                .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Imagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VIndividualJPanelLayout.createSequentialGroup()
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaLabel)
                            .addComponent(SueldoMaxLabel))
                        .addGap(29, 29, 29)
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SueldoMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VIndividualJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloIndividual)
                .addGap(208, 208, 208))
        );
        VIndividualJPanelLayout.setVerticalGroup(
            VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(TituloIndividual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 542, Short.MAX_VALUE)
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FechaLabel)
                            .addComponent(FechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SueldoMaxField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SueldoMaxLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(VIndividualJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFiltrarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FiltrarApellidoButton))
                        .addGap(32, 32, 32)
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroLabel)
                            .addComponent(NumeroField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreLabel)
                            .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoLabel)
                            .addComponent(ApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SueldoLabel)
                            .addComponent(SueldoField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(VIndividualJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RetrocederButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvanzarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        VCompletoPanel.setBackground(new java.awt.Color(41, 44, 51));
        VCompletoPanel.setPreferredSize(new java.awt.Dimension(898, 575));

        TituloIndividual1.setBackground(new java.awt.Color(153, 153, 255));
        TituloIndividual1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        TituloIndividual1.setForeground(new java.awt.Color(237, 187, 88));
        TituloIndividual1.setText("VISUALIZAR COMPLETO");

        Jlist.setBackground(new java.awt.Color(41, 44, 51));
        Jlist.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 4, true));
        Jlist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Jlist.setForeground(new java.awt.Color(204, 204, 204));
        Jlist.setAutoscrolls(false);
        jScrollPane1.setViewportView(Jlist);

        SueldoLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        SueldoLabel1.setForeground(new java.awt.Color(204, 204, 204));
        SueldoLabel1.setText("Hasta");

        SueldoLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        SueldoLabel2.setForeground(new java.awt.Color(204, 204, 204));
        SueldoLabel2.setText("Desde");

        FiltrarButton.setBackground(new java.awt.Color(56, 67, 75));
        FiltrarButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        FiltrarButton.setForeground(new java.awt.Color(205, 205, 205));
        FiltrarButton.setText("Filtrar");
        FiltrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VCompletoPanelLayout = new javax.swing.GroupLayout(VCompletoPanel);
        VCompletoPanel.setLayout(VCompletoPanelLayout);
        VCompletoPanelLayout.setHorizontalGroup(
            VCompletoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VCompletoPanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(VCompletoPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(SueldoLabel2)
                .addGap(18, 18, 18)
                .addComponent(jDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SueldoLabel1)
                .addGap(18, 18, 18)
                .addComponent(jDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(FiltrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(VCompletoPanelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(TituloIndividual1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VCompletoPanelLayout.setVerticalGroup(
            VCompletoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VCompletoPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(TituloIndividual1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VCompletoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SueldoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateDesde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SueldoLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FiltrarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        InicioSesion.setBackground(new java.awt.Color(41, 44, 51));
        InicioSesion.setPreferredSize(new java.awt.Dimension(898, 575));

        jTextFieldUsuario.setBackground(new java.awt.Color(68, 73, 74));
        jTextFieldUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(205, 205, 205));
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        AccederButton.setBackground(new java.awt.Color(56, 67, 75));
        AccederButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        AccederButton.setForeground(new java.awt.Color(205, 205, 205));
        AccederButton.setText("Acceder");
        AccederButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccederButtonActionPerformed(evt);
            }
        });

        jLabelContraseña.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jLabelContraseña.setText("Contraseña");

        jLabelUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuario.setText("Usuario");

        MyTitle1.setBackground(new java.awt.Color(153, 153, 255));
        MyTitle1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        MyTitle1.setForeground(new java.awt.Color(237, 187, 88));
        MyTitle1.setText("- Iniciar sesión");

        jTextFieldContraseña.setBackground(new java.awt.Color(68, 73, 74));
        jTextFieldContraseña.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextFieldContraseña.setForeground(new java.awt.Color(205, 205, 205));

        javax.swing.GroupLayout InicioSesionLayout = new javax.swing.GroupLayout(InicioSesion);
        InicioSesion.setLayout(InicioSesionLayout);
        InicioSesionLayout.setHorizontalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AccederButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(InicioSesionLayout.createSequentialGroup()
                .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioSesionLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelContraseña))
                        .addGap(32, 32, 32)
                        .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(jTextFieldContraseña)))
                    .addGroup(InicioSesionLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(MyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        InicioSesionLayout.setVerticalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioSesionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InicioSesionLayout.createSequentialGroup()
                        .addComponent(MyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(AccederButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        Barra.setBackground(new java.awt.Color(61, 63, 65));
        Barra.setForeground(new java.awt.Color(61, 63, 65));
        Barra.setToolTipText("");

        Inicio.setText("   INICIO   ");
        Inicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Inicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Inicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        Barra.add(Inicio);

        VisualizarIndividual.setText("   VISUALIZAR INDIVIDUAL  ");
        VisualizarIndividual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        VisualizarIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisualizarIndividualMouseClicked(evt);
            }
        });
        VisualizarIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarIndividualActionPerformed(evt);
            }
        });
        Barra.add(VisualizarIndividual);

        VisualizarCompleto.setText("   VISUALIZAR COMPLETO");
        VisualizarCompleto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        VisualizarCompleto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        VisualizarCompleto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        VisualizarCompleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisualizarCompletoMouseClicked(evt);
            }
        });
        VisualizarCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarCompletoActionPerformed(evt);
            }
        });
        Barra.add(VisualizarCompleto);

        setJMenuBar(Barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 1812, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(VIndividualJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1812, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(392, 392, 392)
                    .addComponent(VCompletoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(522, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(InicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                    .addGap(592, 592, 592)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(VIndividualJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addComponent(VCompletoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(250, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(InicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(394, 394, 394)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
        cambiarContenedor(Bienvenida);
    }//GEN-LAST:event_InicioActionPerformed

    private void VisualizarCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarCompletoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_VisualizarCompletoActionPerformed

    private void VisualizarIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarIndividualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisualizarIndividualActionPerformed

    private void VisualizarIndividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisualizarIndividualMouseClicked
        // TODO add your handling code here:
        cambiarContenedor(VIndividualJPanel);
        
        InicioVisualizarIndividual();
        String[] ape = bd.getApellidosDistintos();
        
        for (String a : ape){
            System.out.println(a);
        }
        jComboBoxFiltrarApellido.setModel(new javax.swing.DefaultComboBoxModel<>(bd.getApellidosDistintos()));

        
        
        
    }//GEN-LAST:event_VisualizarIndividualMouseClicked

    

    private void VisualizarCompletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisualizarCompletoMouseClicked
        // TODO add your handling code here:
        cambiarContenedor(VCompletoPanel);
        visualizarEmpleadosCompleto();

    }//GEN-LAST:event_VisualizarCompletoMouseClicked

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        // TODO add your handling code here:
        cambiarContenedor(Bienvenida);

    }//GEN-LAST:event_InicioMouseClicked

    private void NumeroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroFieldActionPerformed

    private void RetrocederButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrocederButtonActionPerformed
        // TODO add your handling code here:
        try{
            retrocederLista();
            mostrarEmpleadoActual();
            AvanzarButton.setEnabled(true);
        }catch(IndexOutOfBoundsException ioobe){
            RetrocederButton.setEnabled(false);
            JOptionPane.showMessageDialog(this, "No hay mas elementos.", "Error", 0);
        }
    }//GEN-LAST:event_RetrocederButtonActionPerformed

    private void AvanzarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanzarButtonActionPerformed
        // TODO add your handling code here:
        try{
            avanzarLista();
            mostrarEmpleadoActual();
            RetrocederButton.setEnabled(true);
        }catch(IndexOutOfBoundsException ioobe){
            AvanzarButton.setEnabled(false);
            JOptionPane.showMessageDialog(this, "No hay mas elementos.", "Error", 0);
        }
    }//GEN-LAST:event_AvanzarButtonActionPerformed

    private void AccederButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccederButtonActionPerformed
        // TODO add your handling code here:
        if(bd.getConnection(jTextFieldUsuario.getText(), jTextFieldContraseña.getText())){
            cambiarContenedor(Bienvenida);
            Barra.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(this, "Las credenciales introducidas son erróneas.", "Error" , 0);
        
    }//GEN-LAST:event_AccederButtonActionPerformed

    private void FiltrarApellidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarApellidoButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(jComboBoxFiltrarApellido.getSelectedItem().toString());
        if(jComboBoxFiltrarApellido.getSelectedItem().toString().equals("ninguno")){
            InicioVisualizarIndividual();
            
        } else{
            lista = bd.getListaFiltrada(jComboBoxFiltrarApellido.getSelectedItem().toString());
            indice = 0;
            actual = lista.get(indice);
            mostrarEmpleadoActual();
            RetrocederButton.setEnabled(false);
            AvanzarButton.setEnabled(true);
        }
    }//GEN-LAST:event_FiltrarApellidoButtonActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void FiltrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarButtonActionPerformed
        // TODO add your handling code here:
        
        System.out.println(getFechaFiltro1());
        filtroFecha();

    }//GEN-LAST:event_FiltrarButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
        
        
    }
    
    private void InicioVisualizarIndividual() {
        lista = bd.getListaEmpleados();
        indice = 0;
        actual = lista.get(indice);
        mostrarEmpleadoActual();
        RetrocederButton.setEnabled(false);
        AvanzarButton.setEnabled(true);
    }
    
    private void mostrarEmpleadoActual() {
        
        NumeroField.setText(actual.getNumero() + "");
        NombreField.setText(actual.getNombre());
        ApellidoField.setText(actual.getApellido());
        SueldoField.setText(actual.getSueldo() + "");
        SueldoMaxField.setText(actual.getSueldoMax() + "");
        FechaField.setText(actual.getFechaAlta().toString());
        var icon = new ImageIcon("img/" + actual.getFoto());
        Image img = icon.getImage();
        icon = new ImageIcon(img.getScaledInstance(204, 174, Image.SCALE_SMOOTH));
        Imagen.setIcon(icon);

    }
    
    private void avanzarLista() {
        actual = lista.get(indice+1);
        indice++;
    }
    
    private void retrocederLista() {
        actual = lista.get(indice-1);
        indice--;
    }
    
    private void visualizarEmpleadosCompleto(){
        
        
        
        lista = bd.getListaEmpleados();
        Object emple;

        DefaultListModel model = new DefaultListModel();
        
        for(int i = 0; i < lista.size(); i++){
            emple = lista.get(i);
            model.addElement(emple);

        }
        
        this.Jlist.setModel(model);
    }
    
    private void filtroFecha(){
        
        String date1 = getFechaFiltro1();
        String date2 = getFechaFiltro2();

    
        listaAux = bd.getListaFiltradaFecha(date1, date2);
        Object emple;
        

        DefaultListModel model = new DefaultListModel();
                    System.out.print("\n");

        for(int i = 0; i < listaAux.size(); i++){
            emple = listaAux.get(i);
            model.addElement(emple);
            System.out.print("\n" + emple);

        }
        
        this.Jlist.setModel(model);
 
    }
    
    public String getFechaFiltro1(){
        //SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");

        String date1 = dFormat.format(jDateDesde.getDate());
        
        
        return date1;

    }

    public String getFechaFiltro2(){

        String date2 = dFormat.format(jDateHasta.getDate());
                
        return date2;

    }
    private void cambiarContenedor(javax.swing.JPanel aux){
      this.setContentPane(aux);
      pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccederButton;
    private javax.swing.JTextField ApellidoField;
    private javax.swing.JLabel ApellidoLabel;
    private javax.swing.JLabel Autores;
    private javax.swing.JButton AvanzarButton;
    private javax.swing.JMenuBar Barra;
    private javax.swing.JPanel Bienvenida;
    private javax.swing.JTextField FechaField;
    private javax.swing.JLabel FechaLabel;
    private javax.swing.JButton FiltrarApellidoButton;
    private javax.swing.JButton FiltrarButton;
    private javax.swing.JLabel Gestiontittle;
    private javax.swing.JLabel Imagen;
    private javax.swing.JMenu Inicio;
    private javax.swing.JPanel InicioSesion;
    private javax.swing.JList<String> Jlist;
    private javax.swing.JLabel MyTitle;
    private javax.swing.JLabel MyTitle1;
    private javax.swing.JTextField NombreField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField NumeroField;
    private javax.swing.JLabel NumeroLabel;
    private javax.swing.JButton RetrocederButton;
    private javax.swing.JTextField SueldoField;
    private javax.swing.JLabel SueldoLabel;
    private javax.swing.JLabel SueldoLabel1;
    private javax.swing.JLabel SueldoLabel2;
    private javax.swing.JTextField SueldoMaxField;
    private javax.swing.JLabel SueldoMaxLabel;
    private javax.swing.JLabel TituloIndividual;
    private javax.swing.JLabel TituloIndividual1;
    private javax.swing.JPanel VCompletoPanel;
    private javax.swing.JPanel VIndividualJPanel;
    private javax.swing.JLabel Version;
    private javax.swing.JMenu VisualizarCompleto;
    private javax.swing.JMenu VisualizarIndividual;
    private javax.swing.JComboBox<String> jComboBoxFiltrarApellido;
    private com.toedter.calendar.JDateChooser jDateDesde;
    private com.toedter.calendar.JDateChooser jDateHasta;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField jTextFieldContraseña;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    

    
}
